name: Continuous Integration
on:
  - push
jobs:
  ci:
    name: Validation
    uses: cncsc/actions/.github/workflows/validation.yaml@main
    runDefaultLinters: false
    additionalHomebrewPackages: shellcheck terragrunt
